### ISSUE TITLE
Submitting new post crashes indexer.js and loom errors

### ISSUE THREAD

**Issue by bartleyg** [loomnetwork/solidity-social-example#2]
The indexer crashes and the loom dappchain throws errors when I try to submit any post.

```
$ ./loom version
1.0.0+b288

$ node --version
v8.11.3

$ elasticsearch --version
Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file logs/gc.log due to No such file or directory

Version: 6.2.4, Build: ccec39f/2018-04-12T20:37:28.497551Z, JVM: 1.8.0_181

$ redis-server --version
Redis server v=4.0.10 sha=00000000:0 malloc=libc bits=64 build=ea14acb2d1b3b56f
```

```
$ ./loom run
I[07-25|03:18:38.597] Using simple log event dispatcher            
I[07-25|03:18:40.867] Starting RPC HTTP server on tcp://127.0.0.1:9999 module=query-server 
D[07-25|03:19:35.696] Running post commit logger                   
I[07-25|03:19:35.696]?

defaultM?A??????<?=*r???
?z,d#??? hi z??iQ?8
I[07-25|03:19:35.696] {Data:[133 155 82 56 119 207 231 52 250 240 138 180 37 42 179 55 2 120 140 60 15 153 4 79 32 38 114 101 51 169 74 204] ValidatorUpdates:[] Info:call.evm Tags:[]} 
D[07-25|03:19:36.676] Running post commit logger                   
I[07-25|03:19:36.676]?

defaultM?A??????<?=*r???
?z,d#??? hi z??iQ?8
I[07-25|03:19:36.676] {Data:[23 95 131 166 85 223 74 184 226 67 92 165 239 157 212 170 148 125 53 183 234 191 51 118 236 43 212 244 76 148 5 58] ValidatorUpdates:[] Info:call.evm Tags:[]} 
2018/07/24 22:19:36 Event emitted: index: 2280, length: 752, msg: {"topics":["0x79ade8575884f3a0d49452aa8c5b8f85237a786d3894d4fe364510b6f05d1fbc"],"caller":{"chain_id":"default","local":"mcklmWx61ORpnxwIUYE4BQ2Weiw="},"address":{"chain_id":"default","local":"TdhBtbT2lQfH6TyiPSpyx/KCF6g="},"plugin_name":"0x4Dd841b5B4F69507C7E93ca23D2A72c7f28217a8","block_height":2280,"encoded_body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAACZySWZbHrU5GmfHAhRgTgFDZZ6LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJoaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","original_request":"I7yq6QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJoaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","tx_hash":"F1+DplXfSrjiQ1yl753UqpR9NbfqvzN27CvU9EyUBTo="}
I[07-25|03:19:36.695] Served RPC HTTP response                     module=query-server method=GET url=/queryws status=200 duration=37631 remoteAddr=127.0.0.1:62920
E[07-25|03:19:36.695] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:62919 err="websocket: close 1006 (abnormal closure): unexpected EOF"
E[07-25|03:19:36.695] Error closing connection                     module=rpc-server protocol=websocket remote=127.0.0.1:62919 err="close tcp 127.0.0.1:46657->127.0.0.1:62919: use of closed network connection"
```

```
$ node indexer.js 
Sending RPC msg to ws://127.0.0.1:9999/queryws, method resolve
Listen on 8081

/Users/bartley/dapps/solidity-social-example/webclient/node_modules/google-protobuf/google-protobuf.js:98
goog.string.splitLimit=function(a,b,c){a=a.split(b);for(var d=[];0<c&&a.length;)d.push(a.shift()),c--;a.length&&d.push(a.join(b));return d};goog.string.editDistance=function(a,b){var c=[],d=[];if(a==b)return 0;if(!a.length||!b.length)return Math.max(a.length,b.length);for(var e=0;e<b.length+1;e++)c[e]=e;for(e=0;e<a.length;e++){d[0]=e+1;for(var f=0;f<b.length;f++)d[f+1]=Math.min(d[f]+1,c[f+1]+1,c[f]+Number(a[e]!=b[f]));for(f=0;f<c.length;f++)c[f]=d[f]}return d[b.length]};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.asserts.errorHandler_=goog.asserts.DEFAULT_ERROR_HANDLER;
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.doAssertFailure_ (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/google-protobuf/google-protobuf.js:99:126)
    at Object.goog.asserts.assert (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/google-protobuf/google-protobuf.js:99:385)
    at jspb.BinaryReader.readMessage (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/google-protobuf/google-protobuf.js:345:139)
    at Function.proto.Event.deserializeBinaryFromReader (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/proto/loom_pb.js:3274:14)
    at Function.proto.Event.deserializeBinary (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/proto/loom_pb.js:3254:22)
    at LoomProvider._onWebSocketMessage (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/loom-provider.js:418:43)
    at Client.<anonymous> (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/loom-provider.js:67:26)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Client._emitContractEvent (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/client.js:403:18)
    at WSRPCClient.emitContractEvent (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/client.js:151:26)
    at emitOne (events.js:116:13)
    at WSRPCClient.emit (events.js:211:7)
    at WebSocket.WSRPCClient._this._onEventMessage (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/loom-js/dist/internal/ws-rpc-client.js:92:23)
    at emitOne (events.js:121:20)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/websocket.js:718:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at Socket.socketOnData (/Users/bartley/dapps/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/websocket.js:788:35)
```

```
$ yarn start
yarn run v1.7.0
warning package.json: No license field
$ webpack-dev-server --hot --content-base ./dist
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/bartley/dapps/solidity-social-example/webclient/dist
⚠ ｢wdm｣: Hash: ed1857b4d7307ae90f66
Version: webpack 4.8.3
Time: 2729ms
Built at: 07/24/2018 10:19:16 PM
    Asset      Size  Chunks                    Chunk Names
bundle.js  3.17 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = bundle.js
 [67] ../node_modules/react-dom/index.js 1.33 KiB {0} [built]
 [99] ../node_modules/webpack/hot/log.js 1.03 KiB {0} [built]
[194] ../node_modules/regenerator-runtime/runtime.js 23.6 KiB {0} [built]
[195] ../node_modules/webpack/hot/emitter.js 77 bytes {0} [built]
[201] ./indexer_client.js 617 bytes {0} [built]
[203] ./post.js 4.76 KiB {0} [built]
[204] ./text.js 3.22 KiB {0} [built]
[455] ./index.js 9.31 KiB {0} [built]
[457] ../node_modules/webpack/hot/dev-server.js 1.66 KiB {0} [built]
[458] ../node_modules/webpack/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[463] ../node_modules/webpack-dev-server/client/overlay.js 3.58 KiB {0} [built]
[465] ../node_modules/webpack-dev-server/client/socket.js 1.05 KiB {0} [built]
[466] ../node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[474] ../node_modules/webpack-dev-server/client?http://localhost:8080 7.75 KiB {0} [built]
[475] multi ../node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server regenerator-runtime/runtime ./index 64 bytes {0} [built]
    + 461 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (3.17 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (3.17 MiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
ℹ ｢wdm｣: Compiled with warnings.
```

**Comment by eduardonunesp** [comment]
@bartleyg thanks for reporting, at the moment I'm working updates and fixes on this repo

**Comment by eduardonunesp** [comment]
@bartleyg The repo is updated, let me know if you run on issues

**Comment by bartleyg** [comment]
Thanks for updating! It doesn't crash when submitting a new post but there are a few issues & concerns. They're all evident on build-288 and build-322.

1. After a post has been submitting, clicking "New Comment" does not do anything.

2. Reloading the page yields an error on the loom console: 
```
I[07-25|22:46:10.443] Served RPC HTTP response                     module=query-server method=GET url=/queryws status=200 duration=162040 remoteAddr=127.0.0.1:61602
E[07-25|22:46:10.444] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:61601 err="websocket: close 1001 (going away)"
E[07-25|22:46:10.444] Error closing connection                     module=rpc-server protocol=websocket remote=127.0.0.1:61601 err="close tcp 127.0.0.1:46657->127.0.0.1:61601: use of closed network connection"
```

3. After reloading the page, when I do a "New Post" the address of the user changes. Is that the expected behavior?

4. Not a problem, just an annoyance. After each transmission on the loom chain, the loom console makes few console alarms in a row.

5. Speed. Just on my local machine I'm seeing anywhere from 0.25 seconds to 1 second between the timestamps on the first loom console output transaction when submitting "New Post" and the follow-on Event emitted. Then add another second or two for the website UI to be refreshed with the new comment. That seems slower than what I expected from the advertised thousands of transactions per second. Can that be sped up?

6. Size. The webclient output from `yarn start` issues a warning that bundle.js is 3.58 MiB and the recommended size limit is 244 KiB.

**Comment by eduardonunesp** [comment]
Is recommended to clean up `node_modules` directory and reinstall by doing `yarn` or `npm install`

1. You should make sure that services like `redis` and `elasticsearch` are running they are required for this example to work.

2. It's ok is just the socket closing connection abruptly.

3. it changes because on this example the address is generated on page view.

4. Yep, not sure why, I think the warnings are on the console if you're using iTerm

5. I believe those are not the same thing, when a transaction happens it's an internal blockchain thing it's pretty fast, also we're using on this example Redis + Elasticache, which will receive the event, process the event on a queue, send the event to Elasticsearch and then the web interface is doing a polling, lot's of things happen. Also, to be clear we only said sub-second blocktimes, and you can fit many transactions per block, but nowhere and no one else has block confirmation times in the realm of 1/1000th of a second. 

6. It's because it should be on development mode and is generating tons of debug info.

**Comment by bartleyg** [comment]
*1.  I did a fresh clone, and cleared redis and elasticsearch. The new comment popup appears to be a browser compatibility issue. It works in Chrome and Safari but does not in Brave, despite disabling shields or enabling popups, cookies, etc.

*5.  Thanks for the clarification. Is it possible for the web interface to poll the dappchain directly for event updates instead of waiting on Redis and Elasticsearch to process them first?

*5b.  Can a user send more than one transaction in a block?

*6.  How do I disable development / debug mode?

Thanks!

**Comment by mattkanwisher** [comment]
5b. so transactions are sequential, you'll need to use multiple private keys, or you have to manually increment the nonce on the client side. if you need to many transactions from a user in a row, this may not be the best usecase for a blockchain.
6b. yeah we identified public builds, have a regressions with the debug settings. next release will have options to disable this.

**Comment by bartleyg** [comment]
@mattkanwisher thanks for the explanation. Good to know the capabilities and limitations of the chain for different use cases. I'm looking forward to future updates!

**Comment by eduardonunesp** [comment]
This example received an update with latest loom sdk
