### ISSUE TITLE
indexer.js & unsupported protocol scheme

### ISSUE THREAD

**Issue by ParkHyeonSeong** [loomnetwork/solidity-social-example#4]
I can not solve this problem

I tried 
```
node indexer.js
``` 
but output error...
this...
```
message { kind: 'error',
  url: 'ws://127.0.0.1:46658/websocket',
  error:
   Error: Unexpected server response: 502
       at ClientRequest.req.on (/Users/ceo/loom/solidity-social-example/webclient/node_modules/rpc-websockets/node_modules/ws/lib/websocket.js:542:5)
       at ClientRequest.emit (events.js:182:13)
       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
       at Socket.socketOnData (_http_client.js:441:20)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onread (net.js:639:20) }
```

and loom terminal also error.
```
http: proxy error: unsupported protocol scheme
```

Start Web Server is same crush
```
http: proxy error: unsupported protocol scheme 
```

I can open web page, but no action when I click anything.... (localhost:8080)

Can you help me? :(

++ add
```
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (3.7 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (3.7 MiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

this warning message is no problem to run web server?

### Thank you for read this issue!

**Comment by eduardonunesp** [comment]
Hi @ParkHyeonSeong could you please inform the version used `loomchain`, `node` and `loom-js`

**Comment by ParkHyeonSeong** [comment]
Hi @eduardonunesp 
I solved this issue that is build version crash!

I am using the latest osx loom version(brew install).
I knew that different build versions would not work at all.

Than you 👍
